# Generated by Django 5.2.4 on 2025-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='reference',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
