# Generated by Django 5.1.3 on 2025-06-04 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_unit_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
