# Generated by Django 5.1.3 on 2025-06-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_variant_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
