# Generated by Django 5.1.3 on 2025-07-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_subcategory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The purchase/cost price of the product', max_digits=10),
        ),
    ]
