# Generated by Django 5.1.3 on 2025-07-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_populate_roles_and_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='new_role',
            new_name='role',
        ),
    ]