# Generated by Django 5.1.3 on 2025-06-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='supplier_images/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('country', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
