# Generated by Django 5.1.3 on 2025-06-08 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
