# Generated by Django 5.1.3 on 2025-07-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, help_text='M-Pesa phone number used for payment', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text='M-Pesa receipt number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa')], default='cash', max_length=10),
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number used for M-Pesa payment', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12)),
                ('merchant_request_id', models.CharField(help_text='M-Pesa Merchant Request ID', max_length=50, unique=True)),
                ('checkout_request_id', models.CharField(help_text='M-Pesa Checkout Request ID', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa receipt number', max_length=20, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, help_text='Date when M-Pesa transaction was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_description', models.TextField(blank=True, null=True)),
                ('customer_message', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='sales.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['checkout_request_id'], name='sales_mpesa_checkou_7cff25_idx'), models.Index(fields=['merchant_request_id'], name='sales_mpesa_merchan_1cfd09_idx'), models.Index(fields=['status'], name='sales_mpesa_status_ee6041_idx')],
            },
        ),
    ]
