# Generated by Django 5.1.3 on 2025-09-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_mpesa_txn_invoice_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='draft', max_length=10),
        ),
    ]
